#!/usr/bin/env bash

git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status

go install golang.org/x/tools/cmd/godoc@latest